### ISSUE TITLE
Firebase Functions cleanDatabase not working

### ISSUE THREAD

**Issue by GewoonMaarten** [GewoonMaarten/iot-watering-system#1]
**Error**:
`TypeError: Cannot read property 'replace' of undefined
    at exports.cleanDatabase.functions.database.ref.onWrite.event (/user_code/index.js:35:42)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:35:20
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

**Comment by GewoonMaarten** [comment]
Fixed. One object didn't have dateTime field. Will update code to handle this.
